export const REQUEST_STATUS_LABELS: Record<string, { label: string; className: string }> = {
  DRAFT: { label: "Brouillon", className: "bg-paperDim text-ink/60" },
  SUBMITTED: { label: "EnvoyÃ©e", className: "bg-gold-soft text-ink" },
  PENDING_VALIDATION: { label: "En attente de validation", className: "bg-gold-soft text-ink" },
  CALL_PENDING: { label: "Appel Ã  venir", className: "bg-gold-soft text-ink" },
  CALL_IN_PROGRESS: { label: "Appel en cours", className: "bg-gold-soft text-ink" },
  CALLBACK_REQUESTED: { label: "Rappel demandÃ©", className: "bg-gold-soft text-ink" },
  NEEDS_INFORMATION: { label: "Informations manquantes", className: "bg-clay-soft text-clay-dark" },
  VALIDATED: { label: "ValidÃ©e", className: "bg-emerald-soft text-emerald-dark" },
  VALIDATED_WITH_CHANGES: { label: "ValidÃ©e (corrigÃ©e)", className: "bg-emerald-soft text-emerald-dark" },
  PUBLISHED: { label: "PubliÃ©e â€” recherche en cours", className: "bg-emerald-soft text-emerald-dark" },
  MATCHING: { label: "Recherche de professionnels", className: "bg-emerald-soft text-emerald-dark" },
  PROFESSIONAL_CONTACTED: { label: "Professionnel contactÃ©", className: "bg-emerald-soft text-emerald-dark" },
  ACCEPTED: { label: "AcceptÃ©e", className: "bg-emerald-soft text-emerald-dark" },
  IN_PROGRESS: { label: "Intervention en cours", className: "bg-emerald-soft text-emerald-dark" },
  COMPLETED: { label: "TerminÃ©e", className: "bg-emerald text-paper" },
  CANCELLED: { label: "AnnulÃ©e", className: "bg-paperDim text-ink/50" },
  EXPIRED: { label: "ExpirÃ©e", className: "bg-paperDim text-ink/50" },
  REJECTED: { label: "RejetÃ©e", className: "bg-clay-soft text-clay-dark" },
  SUSPICIOUS: { label: "En vÃ©rification", className: "bg-clay-soft text-clay-dark" },
};
