export const REQUEST_STATUS_LABELS: Record<string, { label: string; className: string }> = {
  DRAFT: { label: "Brouillon", className: "bg-paperDim text-ink/60" },
  SUBMITTED: { label: "Envoyée", className: "bg-gold-soft text-ink" },
  PENDING_VALIDATION: { label: "En attente de validation", className: "bg-gold-soft text-ink" },
  CALL_PENDING: { label: "Appel à venir", className: "bg-gold-soft text-ink" },
  CALL_IN_PROGRESS: { label: "Appel en cours", className: "bg-gold-soft text-ink" },
  CALLBACK_REQUESTED: { label: "Rappel demandé", className: "bg-gold-soft text-ink" },
  NEEDS_INFORMATION: { label: "Informations manquantes", className: "bg-clay-soft text-clay-dark" },
  VALIDATED: { label: "Validée", className: "bg-emerald-soft text-emerald-dark" },
  VALIDATED_WITH_CHANGES: { label: "Validée (corrigée)", className: "bg-emerald-soft text-emerald-dark" },
  PUBLISHED: { label: "Publiée — recherche en cours", className: "bg-emerald-soft text-emerald-dark" },
  MATCHING: { label: "Recherche de professionnels", className: "bg-emerald-soft text-emerald-dark" },
  PROFESSIONAL_CONTACTED: { label: "Professionnel contacté", className: "bg-emerald-soft text-emerald-dark" },
  ACCEPTED: { label: "Acceptée", className: "bg-emerald-soft text-emerald-dark" },
  IN_PROGRESS: { label: "Intervention en cours", className: "bg-emerald-soft text-emerald-dark" },
  COMPLETED: { label: "Terminée", className: "bg-emerald text-paper" },
  CANCELLED: { label: "Annulée", className: "bg-paperDim text-ink/50" },
  EXPIRED: { label: "Expirée", className: "bg-paperDim text-ink/50" },
  REJECTED: { label: "Rejetée", className: "bg-clay-soft text-clay-dark" },
  SUSPICIOUS: { label: "En vérification", className: "bg-clay-soft text-clay-dark" },
};
